---
title: "Nigeria: WASH data"
output: html_notebook
---

```{r setup, include=TRUE}
library(tidyverse)
```

```{r read_wash, include=TRUE}
df_wash <- readxl::read_xlsx('.//data/ObservationData_WASH.xlsx', sheet = 'ObservationData') %>% 
  rename('state' = 'States Name',
         'indicator' = 'Indicators Name',
         'indicator_long' = 'Indicators - FULLNAME') %>% 
  select(state, indicator, indicator_long, '2009') %>% 
  mutate(wash_type = case_when(grepl("Drink", 
                                     indicator_long) ~ "Water",
                            grepl("Toilet", 
                                  indicator_long, ignore.case = TRUE) ~"Sanitation")) %>% 
  filter(complete.cases(.))
```

```{r write_wash, include=TRUE}
df_wash %>% 
  distinct(indicator, wash_type) %>% 
  write_csv(., './/data_output/wash_types.csv')
```

```{r df_wash_2, include=TRUE}
df_wash_2 <- df_wash %>% 
  left_join(x=.,
            y=readxl::read_xlsx('.//data/wash_mapping.xlsx'),
            by='indicator')
```

```{r df_wash_3, include=TRUE}
df_wash_3 <- df_wash_2 %>% 
  group_by(state,
           IFs_var, 
           wash_type) %>% 
  summarise(`2009` = sum(`2009`, na.rm = TRUE))
```

```{r wash_2017, include=TRUE}
wash_2017 <- readxl::read_xlsx('.//data/wash_2017.xlsx', 
                               sheet='data') %>% 
  gather(IFs_var, `2017`, 4:7)
  
wash_total <- left_join(x=df_wash_3 %>% 
                          filter(wash_type == 'Sanitation'),
                        y=wash_2017,
                        by=c('state', 'IFs_var')) %>% 
  select(state_ifs, IFs_var, `2009`, `2017`) %>% 
  write_csv(., './/data_output/sanitation_table.csv')
```

```{r water_2017, include=TRUE}
water_2017 <- readxl::read_xlsx('.//data/wash_2017.xlsx', 
                               sheet='data_water') %>% 
  gather(IFs_var, `2017`, 4:6)

left_join(x=df_wash_3 %>% 
            filter(wash_type == 'Water'),
          y=water_2017,
          by=c('state', 'IFs_var')) %>% 
  select(state_ifs, IFs_var, `2009`, `2017`) %>% 
  write_csv(., './/data_output/water_table.csv')
```
